### ISSUE TITLE
read only section of a large series?

### ISSUE THREAD

**Issue by rjlopez2** [fujiisoup/sif_parser#15]
I wander if it is possible to implement a feature (if does not exist yet) for (partially) reading only a section of the series array, lets say small ROI or only few frames. This I think might be particularly useful when handling large datasets. For assistance to the `np_open`  [function](https://github.com/fujiisoup/sif_parser/blob/2e5721430cdcf080fdf1382b6930ae0fb97415af/sif_parser/sif_open.py#L8) add new arguments for the desire range?

**Comment by fujiisoup** [comment]
Hi, @rjlopez2 .
This is a good suggestion. I think we can use [numpy.memmap](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html), which supports indexing similar to a normal array. 
Do you mind contributing?

**Comment by rjlopez2** [comment]
Hey @fujiisoup 

I would be super glad to give it a shot, but since I am learning programming, it make take a bit until I go trough the logic of your parsing routine and implement some barely working example. Thanks already for pointing to some resources!
For my particular application I was actually wandering whether makes sense to wrap the function using the library dask for lazy load and then read-on-demand the chunk or segment of data you want to have a look at. Still not sure if this is a good idea plus will require an additional dependency :/
Anyway... I will try to give it a try and see what come up. May need to ask you for support at some point...

cheers

Ruben

**Comment by fujiisoup** [comment]
Hi @rjlopez2 

I quickly added a rough implementation at
https://github.com/fujiisoup/sif_parser/blob/47d03a61e8d920c9dad45fd0f1d31b5b2fb212a2/sif_parser/sif_open.py#L8

Is it something you expected?
We may still want full tests, for example to test
- if the array is not in memory
- if the array is indexable
and we may need `xr_open` to support this lazy read (it should be pretty straight forward though, as xarray naturally supports dask).

If you could pull this branch, refine it, and make a pull request, it would be very much appreciated.

**Comment by rjlopez2** [comment]
Hey 

> Is it something you expected?

I will test it and come back soon with feedback.

btw that was blazing fast ;) thanks

**Comment by fujiisoup** [comment]
Closed by #17
