### ISSUE TITLE
matplotlib conflict when importing sif_parser is breaking pyplot.plot 

### ISSUE THREAD

**Issue by davesmivers** [fujiisoup/sif_parser#20]
Unbuntu 22.04
Python 3.10.6
Minimal virtual environment

I'm getting this error...

Exception has occurred: UnicodeDecodeError
'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

This doesn't work....

import sif_parser as sif
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,2,1,2])
plt.show()

This does work...

#import sif_parser as sif
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,2,1,2])
plt.show()

Digging down a little if I comment out line 23 in the 'plugin' module of sif_parser:

#Image.register_open("SIF", SifImageFile)

then this works again

**Comment by fujiisoup** [comment]
It is wired... I can't reproduce this in my environment.
Colabo also works fine
https://colab.research.google.com/drive/1BoezvuKMFCJJDg-3smFQjDgkmpEp2hff?usp=share_link

Which environment do you use?
Pillow is imported by chance?
We have a problem with Pillow. see #14.

**Comment by mruijzendaal** [comment]
@fujiisoup Could you implement a fix using this method?

**Comment by fujiisoup** [comment]
I will, but probably this weekend.  Sorry for my late response.

**Comment by mruijzendaal** [comment]
Thanks a lot!
