### ISSUE TITLE
not able to read SoMat Information files (SIF) through the following package 

### ISSUE THREAD

**Issue by msrpy** [fujiisoup/sif_parser#24]
It shows issue of encoding for such SIF files, please look into the same, as i have attached the zip containing the SIF file. 
 a UnicodeDecodeError is raised
[test.zip](https://github.com/fujiisoup/sif_parser/files/12924561/test.zip)

**Comment by fujiisoup** [comment]
Thank you for raising this issue.

I can reproduce the error. But this file does not look like a SIF file. 
The first line of the standard SIF file (when opened in a text editor) should be `Andor Technology Multi-Channel File`, but there are many invisible unicodes letters in the first line.

How did you make this file? Was it made by Andor SIF?

**Comment by msrpy** [comment]
Yes, I too noticed that, this is not a Andor SIF file, but it is a SOMAT sif file used to store measurement data. This file is made by SOMAT systems. Is there a way to parse such files and read such files.

**Comment by fujiisoup** [comment]
I have never worked with SOMAT information system. Do you have the details of the format? 
My guess is that they are different format...

**Comment by msrpy** [comment]
that is the thing I don't have sufficient documentation for the same, thus having issues with parsing such files

**Comment by fujiisoup** [comment]
So, it seems like a different format, and supporting this format might not be easy. Let me close this issue.
