### ISSUE TITLE
np_open has trouble reading cascaded sif file

### ISSUE THREAD

**Issue by RounakChatterjee** [fujiisoup/sif_parser#29]
In kinetic mode of Andor whenever the number of images exceeds 4GB it splits the excess files and saves. np_open can't open the extra file if the file isn't 4GB big. It shows the following error in the code section of 

sif_parser\_sif_open.py: 204 in _open(fp)

201 info['ybin'] = ybin
203 for f in range(no_images):
204        info['timestamp_of_{0:d}'.format(f)] = int(fp.readline())  <---
206 offset = fp.tell()
207 try: # remove extra 0 if it exits.

ValueError: invalid literal for int() with base 10: b'      

This only happens when the last file of the split ".sif" files set is not  a complete 4GB file. Any other file the comes in between and is 4GB is read perfectly with the info present. 

I used both the pip version 0.3.0 and  built and installed github version 0.3.5. Both of them has this issue. This issue is not a computer issue either since it has been seen on multiple systems we use.

**Comment by fujiisoup** [comment]
@RounakChatterjee Thank you for raising the issue and I am sorry for my late response.
Could you upload your file anywhere? I am happy to explore this issue, but it would be easier to work with your files.

**Comment by RounakChatterjee** [comment]
https://drive.google.com/file/d/1G-7jNSp-3CxndpIKNT_uQO4EeNVqBFuQ/view?usp=sharing

You can take the file from this link. It's a google drive link.

**Comment by RounakChatterjee** [comment]
It's working fine now thank you so much. please commit this to original branch

**Comment by fujiisoup** [comment]
Thank you for confirmation. Merged
