### ISSUE TITLE
Added to PyPI Test | RFC

### ISSUE THREAD

**Issue by bicarlsen** [fujiisoup/sif_parser#3]
I've added the package to the PyPI test server for review. If there are any changes to make please comment on them here. Otherwise give the okay and I will post it on the production server.

[TestPyPI/sif_parser](https://test.pypi.org/project/sif-parser/0.3.0/)

**Comment by fujiisoup** [comment]
Looks great! Thank you

**Comment by bicarlsen** [comment]
The package has been added to PyPI @ https://pypi.org/project/sif-parser/0.3.0/
