### ISSUE TITLE
Gate Width is missing 

### ISSUE THREAD

**Issue by luoris-luo** [fujiisoup/sif_parser#37]
Hi there,

Thanks for your brilliant sif_parser. But I found the Gate width is missing in the metadata. Also the gate width seems wrong (it should be 4000ns instead of 0ns). 

I would like to help upgrade the code, but it seems a bit difficult to me. Or am I missing something?
Any advice is much appreciated!!!!

Luo

**Comment by fujiisoup** [comment]
Hi

Thank you for raising an issue. Yes, the metadata is still insufficient.
Could you upload your sif file to this issue? If you compress your sif file into a zip file, you can upload here.

**Comment by luoris-luo** [comment]
[for sif_parser.zip](https://github.com/user-attachments/files/16156810/for.sif_parser.zip)

Hi, thanks for the kind reply. I have uploaded the files here.
Sorry for the late reply but I was making sure with the university regulators if this violates related policy.

ご返信ありがとうございました。ファイルはここにアップロードしました。
返信は遅いのですみませんでした、これが関連ポリシーに違反していないかどうかを確認していました。
よろしくお願いします！

**Comment by fujiisoup** [comment]
Hi luo

Thank you for uploading the files.
I have fixed the source and merged into master.

Now your file looks like this, with `GateDelay`, `GateWidth` in second and `GateGain`
![image](https://github.com/fujiisoup/sif_parser/assets/6815844/6cc469a0-0354-48be-b28a-66db867b9213)

イシューの投稿、どうもありがとうございました！
