### ISSUE TITLE
Cannot calculate wavelength axis for spectra acquired using 'Step and Glue'

### ISSUE THREAD

**Issue by mimurrayy** [fujiisoup/sif_parser#39]
Hi there!

When using the "Step and Glue" feature of an Andor grating spectrometer, the wavelength axis calculated by `sif_parser.utils.extract_calibration` ends up being smaller than the acquired data. Using "Step and Glue" the spectrometer moves to different wavelength positions, acquires a spectrum, and then moves again. The resulting spectrum contains all the acquired data. However, the calculated wavelength axis seems to only correspond to a single step of the process. Consequently, `sif_parser.utils.parse()` will also fail.

### Example File:
The zip contains both the .sif file as well as the corresponding .asc exported by Solis:
[step_and_glue.zip](https://github.com/user-attachments/files/17494607/step_and_glue.zip)

### Example Script:
``` python
import sif_parser
import numpy as np

path = "./test files/step_and_glue.sif"
data, info = sif_parser.np_open(path)
x = sif_parser.utils.extract_calibration(info)
y = data[0][0] 
print(len(x), len(y)) # returns 1024 4711

(data, info) = sif_parser.utils.parse(path)
# returns: ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1024 and the array at index 1 has size 4711
```

**Comment by fujiisoup** [comment]
Thank you, @mimurrayy, for raising this issue. I have never used this functionality.
I was able to reproduce the issue. I will try working for this.

**Comment by fujiisoup** [comment]
OK. It was an easy fix. Done and merged.
Thank you for your contribution!
